Models/Login.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GWI.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Campo Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 10, ErrorMessage = "Mínimo de 10 e máximo de 30 caracteres.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Senha obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Mínimo de 6 e máximo de 15 caracteres.")]
        public string Senha { get; set; }


        [Required(ErrorMessage = "Campo Tipo do Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 15 caracteres.")]
        public string tipoUser { get; set; }
        public Login()
        {
            this.Email = "";
            this.Senha = "";
            this.tipoUser = string.Empty;
        }    
    }
}

Models/Pessoa.Model/Pessoas.cs
using System.ComponentModel.DataAnnotations;

namespace GWI.Models.Pessoa.Model
{
    public class Pessoas
    {
        private string Senha { get; set; }

        private bool Ativo;
        private int Id_pess { get; set; }

        [Required(ErrorMessage = "Campo Nome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 10 e máximo de 50 caracteres.")]
        private string Nome { get; set; }

        [Required(ErrorMessage = "Campo Sobrenome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 10 e máximo de 50 caracteres.")]
        private string Sobrenome { get; set; }

        [Required(ErrorMessage = "Campo Nome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 10 e máximo de 500 caracteres.")]
        private List<string> Telefone { get; set; }

        [Required(ErrorMessage = "Campo Nome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 10 e máximo de 500 caracteres.")]
        private List<string> Email { get; set; }

        public class Usuario : Pessoas
        {

        }

        public class Administrador : Pessoas
        {

        }

        public class Autor : Pessoas
        {
            private string Cidade { get; set; }
        }
        public Pessoas()
        {
            Senha = string.Empty;
            Ativo = false;
            Id_pess = 0;
            Nome = string.Empty;
            Sobrenome = string.Empty;
            Telefone = string.Empty;
            Email = string.Empty
        }

    }
}

Models/Pessoas.cs
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GWI.Models
{
    public class Pessoas
    {
        public string p_senha { get; set; }

        public bool p_ativo;
        public int p_id { get; set; }

        [Required(ErrorMessage = "Campo Nome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 50 caracteres.")]
        public string p_nome { get; set; }

        [Required(ErrorMessage = "Campo Sobrenome obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 50 caracteres.")]
        public string p_sobrenome { get; set; }

        [Required(ErrorMessage = "Campo telefone obrigatório", AllowEmptyStrings = false)]
        [StringLength(12, MinimumLength = 11, ErrorMessage = "Mínimo de 11 e máximo de 12 caracteres.")]
        public string p_telefone { get; set; }

        [Required(ErrorMessage = "Campo email obrigatório", AllowEmptyStrings = false)]
        [StringLength(50, MinimumLength = 6, ErrorMessage = "Mínimo de 6 e máximo de 50 caracteres.")]
        public string p_email { get; set; }

        public int p_nv_id { get; set; }

        public string p_username { get; set; }

        public Pessoas()
        {
            p_senha = string.Empty;
            p_ativo = false;
            p_id = 0;
            p_nome = string.Empty;
            p_sobrenome = string.Empty;
            p_telefone = string.Empty;
            p_email = string.Empty;
            p_ativo = true;
            p_username = string.Empty;
            p_nv_id = 4;
        }
    }
}

Models/Pessoas/Login.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GWI.Models.Pessoas
{
    public class Login
    {
        [Required(ErrorMessage = "Campo Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 10, ErrorMessage = "Mínimo de 10 e máximo de 30 caracteres.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Senha obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Mínimo de 6 e máximo de 15 caracteres.")]
        public string Senha { get; set; }


        [Required(ErrorMessage = "Campo Tipo do Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 15 caracteres.")]
        public string tipoUser { get; set; }
        public Login()
        {
            Email = "";
            Senha = "";
            tipoUser = string.Empty;
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using GWI.Models;
using GWI.Repositories.ADO.SQLServer;

namespace GWI.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult CadastrarUsuario()
        {
            return View();
        }

        public IActionResult VerificarEmail()
        {
            return View();
        }

        public IActionResult ErroEmail()
        {
            return View();
        }

        public IActionResult EscolherMetodo()
        {
            return View();
        }

        public IActionResult MetodoIncorreto()
        {
            return View();
        }

        public IActionResult InserirCodigo()
        {
            return View();
        }

        public IActionResult NovaSenha()
        {
            return View();
        }
    }
}

Controllers/NoticiasController.cs
using Microsoft.AspNetCore.Mvc;
using GWI.Repositories.ADO.SQLServer;
using GWI.Models.Noticias;
using GWI.Models.Imagens;
using System.Configuration;

namespace GWI.Controllers
{
    public class NoticiasController : Controller
    {
        private readonly Repositories.ADO.SQLServer.NoticiaADO repository;

        public NoticiasController(IConfiguration configuration)
        { 
            this.repository = new Repositories.ADO.SQLServer.NoticiaADO(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
        }

        // Crud de Notícia //
        #region
        [HttpGet]
        public ActionResult Index()
        {
            return View(this.repository.get());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(this.repository.GetById(id));
        }

        [HttpGet]
        public ActionResult Create(int p_id)
        {
            ViewBag.p_id = 3;
            ViewBag.CategoriasList = this.repository.GetCategorias();
            ViewBag.SubcategoriasList = this.repository.GetSubcategorias();
            ViewBag.ImagensList = this.repository.GetImagens();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Noticias noticias, int p_id)
        {
            try
            {
                noticias.nt_p_id = p_id;
                this.repository.add(noticias);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(this.repository.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Noticias noticias)
        {
            try
            {
                this.repository.update(id, noticias);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            this.repository.delete(id);
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Controllers/PessoasController.cs
using GWI.Services;
using GWI.Repositories.ADO.SQLServer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using GWI.Models.Pessoas;
using System.Linq.Expressions;

namespace GWI.Controllers
{
    public class PessoasController : Controller
    {
        private readonly PessoaADO repository;
        private readonly ISessao sessao;

        public PessoasController(IConfiguration configuration, ISessao sessao)
        { 
            this.repository = new PessoaADO(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
            this.sessao = sessao;
        }

        //  Métodos de Login  //
        #region

        public IActionResult Login()
        {
            return this.sessao.getTokenPessoas() == null ?  View() : RedirectToAction("Index", "Pessoas");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Pessoas pessoas)
        {

            if (!string.IsNullOrEmpty(pessoas.p_email) && !string.IsNullOrEmpty(pessoas.p_senha))
            {
                if (this.repository.check(pessoas))
                {
                    var loginResultado = repository.getType(pessoas);
                    this.sessao.addTokenPessoas(pessoas);

                    switch (loginResultado.TipoUsuario) {
                        case 1:
                            return RedirectToAction(nameof(AcessarPerfilAdm), new { id = pessoas.p_id });
                        case 4:
                            return RedirectToAction(nameof(AcessarPerfilUsuario), new { id = pessoas.p_id });
                    }
                }
                ModelState.AddModelError(string.Empty, "Usuário e/ou Senha Inválidos!");
            }
            ViewBag.Error = "Usuario não detectado";
            return View();
        }

        public IActionResult Logout()
        {
            this.sessao.deleteTokenPessoas();
            return RedirectToAction("Index", "Noticias");
        }
        #endregion


        // Crud de Pessoa //
        #region
        [HttpGet]
        public ActionResult Index()
        {
            return View(this.repository.get());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        [Route("CreateByAdm")]
        public ActionResult Create(int nv, int us_id)
        {
            ViewBag.nvUser = nv;
            ViewBag.idUser = us_id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pessoas pessoas, int nv, int us_id)
        {
            try
            {
                this.repository.add(pessoas);
                switch (nv)
                {
                    case 1:
                        return RedirectToAction(nameof(AcessarPerfilAdm), new { id = us_id });

                    default:
                        return RedirectToAction(nameof(Login));
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id, int nv, int us_id)
        {
            ViewBag.nvUser = nv;
            ViewBag.idUser = us_id;
            return View(this.repository.GetById(id));
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, int nv, int us_id, Pessoas pessoas)
        {
            try
            {
                this.repository.update(id, pessoas);
                switch (nv)
                {
                    case 1:
                        return RedirectToAction(nameof(AcessarPerfilAdm), new { id = us_id });

                    default:
                        return RedirectToAction(nameof(AcessarPerfilUsuario), new { id = id });
                }
            }
            catch
            {
                return View();
            }
        }
       
        public ActionResult Delete(int p_id, int nv, int us_id)
        {
            this.repository.delete(p_id);
            switch (nv)
            {
                case 1:
                    return RedirectToAction(nameof(AcessarPerfilAdm), new { id = us_id });

                default:
                    return RedirectToAction("Index", "Noticias");
            }
        }
        #endregion


        // Métodos de Perfil //
        #region

        #region"Padrão"

                public IActionResult AcessarPerfilUsuario(int id)
                {
                    return View(this.repository.GetById(id));
                }

                #endregion

        #region"ADM"

        public IActionResult AcessarPerfilAdm(int id)
        {
            List<List<Pessoas>> pessoas = this.repository.get();
            ViewBag.ListPadrao = pessoas[0];
            ViewBag.ListAutor = pessoas[1];
            ViewBag.ListAdm = pessoas[2];
            return View(this.repository.GetById(id));
        }

        #endregion

        #endregion
    }
}

Controllers/PessoasCurriculosController.cs
using GWI.Services;
using GWI.Repositories.ADO.SQLServer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using GWI.Models.Curriculos;
using GWI.Models.Noticias;
using GWI.Models;

namespace GWI.Controllers
{
    public class PessoasCurriculosController : Controller
    {
        private readonly Repositories.ADO.SQLServer.PessoasCurriculosADO repository;
        private readonly Services.ISessao sessao;

        public PessoasCurriculosController(IConfiguration configuration, Services.ISessao sessao)
        {
            this.repository = new Repositories.ADO.SQLServer.PessoasCurriculosADO(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
            this.sessao = sessao;
        }

        // Curriculo Completo //
        #region
        public ActionResult CurriculoCompleto(int p_id)
        {
            ViewBag.CnhList = this.repository.GetCnhs();
            ViewBag.HabilidadeList = this.repository.GetHabilidades();
            ViewBag.FeList = this.repository.GetForExps(p_id);
            ViewBag.Pessoa = this.repository.GetByIdPessoa(p_id);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CurriculoCompleto(CurriculoCompleto cr, int p_id)
        {
            try
            {
                cr.P_Id = p_id;
                this.repository.CreateCurriculo(cr);
                return RedirectToAction(nameof(GetCurriculo), new { cr = cr });
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public ActionResult GetCurriculo(CurriculoCompleto cr)
        {
            this.repository.GetCurriculo();
            return View();
        }
        #endregion

        // Crud de Formação e Experiência Profissional //
        #region
        [HttpGet]
        public ActionResult Index(int p_id)
        {
            ViewBag.p_id = p_id;
            return View(this.repository.GetForExps(p_id));
        }

        [HttpGet]
        public ActionResult Create(int p_id)
        {
            ViewBag.p_id = p_id;
            ViewBag.AreasList = this.repository.GetAreas();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ForExp forExp, int p_id)
        {
            try
            {
                forExp.fe_p_id = p_id;
                this.repository.CreateForExp(forExp);

                return RedirectToAction(nameof(Index), new { p_id = p_id});
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int fe_id, int p_id) 
        {
            this.repository.DefDelete(fe_id);
            return RedirectToAction(nameof(Create), new { p_id = p_id });
        }

        [HttpGet]
        public ActionResult Delete(int fe_id, int p_id)
        {
            this.repository.DefDelete(fe_id);
            return RedirectToAction(nameof(Index), new { p_id = p_id});
        }

        //[HttpGet]
        //public ActionResult Edit(int id, int p_id)
        //{
        //    ViewBag.p_id = p_id;
        //    ViewBag.AreasList = this.repository.GetAreas();
        //    return View(this.repository.GetByIdForExp(id));
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int p_id, ForExpArea forExp)
        //{
        //    try
        //    {
        //        ViewBag.AreasList = this.repository.GetAreas();
        //        this.repository.UpdateForExp(forExp);
        //        return RedirectToAction(nameof(Index), new { p_id = p_id });
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        #endregion
    }
}

Views/Pessoas/AcessarPerfilAdm.cshtml
@model GWI.Models.Pessoas.Pessoas;

@{
    ViewData["Title"] = "AcessarPerfilUsuario";
}


<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <section class="section-perfil">
        <img src="">

        <a asp-controller="Pessoas" asp-action="Edit" asp-route-id="@Model.p_id">Editar Perfil</a>

        <h2>@Html.DisplayFor(model => model.p_username)</h2>

        <p>@Html.DisplayFor(model => model.p_nome) @Html.DisplayFor(model => model.p_sobrenome)</p>
        <p>@Html.DisplayFor(model => model.p_telefone)</p>
        <p>@Html.DisplayFor(model => model.p_email)</p>

        <!-- listar usuários -->
        <h2>Usuários</h2>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userOne" aria-expanded="false" aria-controls="userOne">
                        Usuários Padrão
                    </button>
                </h2>
                <div id="userOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <table>
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Username</th>
                                    <th>Nome</th>
                                    <th>Sobrenome</th>
                                    <th>Email</th>
                                    <th>Telefone</th>
                                    <th>Documento</th>
                                    <th><a class="btn btn-primary" role="button" asp-controller="Pessoas" asp-action="CreateByAdm" asp-route-nv="@Model.p_nv_id" asp-route-us_id="@Model.p_id">Adicionar</a></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (GWI.Models.Pessoas.Pessoas pessoas in ViewBag.ListPadrao)
                                {
                                    <tr>
                                        <td>@pessoas.p_id</td>
                                        <td>@pessoas.p_username</td>
                                        <td>@pessoas.p_nome</td>
                                        <td>@pessoas.p_sobrenome</td>
                                        <td>@pessoas.p_email</td>
                                        <td>@pessoas.p_telefone</td>
                                        <td>docs</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-primary" role="button" asp-controller="Pessoas" asp-action="Edit" asp-route-id="@pessoas.p_id" asp-route-nv="@Model.p_nv_id" asp-route-us_id="@Model.p_id">Editar</a>
                                                <a class="btn btn-danger" role="button" asp-controller="Pessoas" asp-action="Delete" asp-route-p_id="@pessoas.p_id" asp-route-nv="@Model.p_nv_id" asp-route-us_id="@Model.p_id">Remover</a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userTwo" aria-expanded="false" aria-controls="userTwo">
                        Autores
                    </button>
                </h2>
                <div id="userTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <table>
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Username</th>
                                    <th>Nome</th>
                                    <th>Sobrenome</th>
                                    <th>Email</th>
                                    <th>Telefone</th>
                                    <th>Documento</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (GWI.Models.Pessoas.Pessoas pessoas in ViewBag.ListAutor)
                                {
                                    <tr>
                                        <td>@pessoas.p_id</td>
                                        <td>@pessoas.p_username</td>
                                        <td>@pessoas.p_nome</td>
                                        <td>@pessoas.p_sobrenome</td>
                                        <td>@pessoas.p_email</td>
                                        <td>@pessoas.p_telefone</td>
                                        <td>docs</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userThree" aria-expanded="false" aria-controls="userThree">
                        Administradores
                    </button>
                </h2>
                <div id="userThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <table>
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Username</th>
                                    <th>Nome</th>
                                    <th>Sobrenome</th>
                                    <th>Email</th>
                                    <th>Telefone</th>
                                    <th>Documento</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (GWI.Models.Pessoas.Pessoas pessoas in ViewBag.ListAdm)
                                {
                                    <tr>
                                        <td>@pessoas.p_id</td>
                                        <td>@pessoas.p_username</td>
                                        <td>@pessoas.p_nome</td>
                                        <td>@pessoas.p_sobrenome</td>
                                        <td>@pessoas.p_email</td>
                                        <td>@pessoas.p_telefone</td>
                                        <td>docs</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- logout -->
        <a asp-controller="Pessoas" asp-action="Logout">LogOut</a>
    </section>
</main>

Views/Pessoas/AcessarPerfilUsuario.cshtml
@model GWI.Models.Pessoas.Pessoas

@{
    ViewData["Title"] = "AcessarPerfilUsuario";
}


<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <section class="section-perfil">
        <img src="">

        <a asp-controller="Pessoas" asp-action="Edit" asp-route-id="@Model.p_id">Editar Perfil</a>

        <h2>@Html.DisplayFor(model => model.p_username)</h2>

        <p>@Html.DisplayFor(model => model.p_nome) @Html.DisplayFor(model => model.p_sobrenome)</p>
        <p>@Html.DisplayFor(model => model.p_telefone)</p>
        <p>@Html.DisplayFor(model => model.p_email)</p>

        <a asp-controller="PessoasCurriculos" asp-action="Index" asp-route-p_id="@Model.p_id">Add Infos Curriculo</a>

        <h3>Meus Curriculos</h3>
        <button>Editar Curriculos</button>
        <!-- carrossel de curriculos-->
        <div></div>

        <h3>Noticias Favoritas</h3>
        <a>Editar Favoritos</a>
        <!-- carrossel de noticias salvas-->
        <div></div>

        <!-- logout -->
        <a asp-controller="Pessoas" asp-action="Logout">LogOut</a>
    </section>
</main>

Views/Pessoas/Create.cshtml
@model GWI.Models.Pessoas.Pessoas

@{
    ViewData["Title"] = "Create";
}

<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro">
        <h2 class="titulo-cadastro">Cadastro</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <form class="form-cadastro" asp-controller="Pessoas" asp-action="Create" asp-route-nv="@ViewBag.nvUser ?? 0" asp-route-us_id="@ViewBag.idUser ?? 0">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <label asp-for="p_nome" class="label-cadastro" for="p_nome">Primeiro Nome:</label>
            <input asp-for="p_nome" class="input-cadastro" type="text" name="p_nome" placeholder="Ex: Joãozinho">
            <span asp-validation-for="p_nome" class="text-danger"></span>

            <label asp-for="p_sobrenome" class="label-cadastro" for="p_sobrenome">Sobrenomes:</label>
            <input asp-for="p_sobrenome" class="input-cadastro" type="text" name="p_sobrenome" placeholder="Ex: Sobrenome1 Sobrenome2...">
            <span asp-validation-for="p_sobrenome" class="text-danger"></span>

            <label asp-for="p_username" class="label-cadastro" for="p_username">Usernam:</label>
            <input asp-for="p_username" class="input-cadastro" type="text" name="p_username" placeholder="Ex: jps123">
            <span asp-validation-for="p_username" class="text-danger"></span>

            <label asp-for="p_telefone" class="label-cadastro" for="p_telefone">Telefone:</label>
            <input asp-for="p_telefone" class="input-cadastro" type="tel" name="p_telefone" placeholder="16998876473">
            <span asp-validation-for="p_telefone" class="text-danger"></span>

            <label asp-for="p_email" class="label-cadastro" for="email">Email:</label>
            <input asp-for="p_email" class="input-cadastro" type="email" name="p_email" placeholder="Ex: joaozinho@email.com">
            <span asp-validation-for="p_email" class="text-danger"></span>

            <label asp-for="p_senha" class="label-cadastro" for="senha">Senha:</label>
            <input asp-for="p_senha" class="input-cadastro" type="password" name="p_senha">
            <span asp-validation-for="p_senha" class="text-danger"></span>

            @* <label asp-for="p_nv_id" class="label-cadastro" for="p_nv_id">Nivel:</label>
            <input asp-for="p_nv_id" class="input-cadastro" type="number" name="p_nv_id">
            <span asp-validation-for="p_nv_id" class="text-danger"></span> *@

            <div class="form-group">
                <input type="submit" value="Create" class="submit-cadastro">
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }
    </section>
</main>

Views/Pessoas/Login.cshtml
@model GWI.Models.Pessoas.Pessoas;

@{
    ViewData["Title"] = "Login";
}

<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro login">
        <h2 class="titulo-cadastro">Login</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <form class="form-cadastro" asp-controller="Pessoas" asp-action="Login">
            <label asp-for="p_email" class="label-cadastro" for="email">Email:</label>
            <input asp-for="p_email" class="input-cadastro" type="email" name="p_email" placeholder="Ex: joaozinho@email.com">
            <span asp-validation-for="p_email" class="text-danger"></span>

            <label asp-for="p_senha" class="label-cadastro" for="senha">Senha:</label>
            <input asp-for="p_senha" class="input-cadastro" type="password" name="p_senha">
            <span asp-validation-for="p_senha" class="text-danger"></span>
            <div>
                <input class="submit-cadastro dois-botoes-esquerda" type="submit" value="Entrar">
                <a asp-controller="Pessoas" asp-action="Create">
                    <button class="submit-cadastro dois-botoes-direita" type="button">Cadastre-Se</button>
                </a>
            </div>
        </form>
    </section>
</main>