Models/Login.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GWI.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Campo Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 10, ErrorMessage = "Mínimo de 10 e máximo de 30 caracteres.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Senha obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Mínimo de 6 e máximo de 15 caracteres.")]
        public string Senha { get; set; }


        [Required(ErrorMessage = "Campo Tipo do Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 15 caracteres.")]
        public string tipoUser { get; set; }
        public Login()
        {
            this.Email = "";
            this.Senha = "";
            this.tipoUser = string.Empty;
        }    
    }
}

Models/Pessoas/Login.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GWI.Models.Pessoas
{
    public class Login
    {
        [Required(ErrorMessage = "Campo Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 10, ErrorMessage = "Mínimo de 10 e máximo de 30 caracteres.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Senha obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Mínimo de 6 e máximo de 15 caracteres.")]
        public string Senha { get; set; }


        [Required(ErrorMessage = "Campo Tipo do Usuário obrigatório", AllowEmptyStrings = false)]
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Mínimo de 3 e máximo de 15 caracteres.")]
        public string tipoUser { get; set; }
        public Login()
        {
            Email = "";
            Senha = "";
            tipoUser = string.Empty;
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using GWI.Models;
using GWI.Repositories.ADO.SQLServer;

namespace GWI.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult CadastrarUsuario()
        {
            return View();
        }

        public IActionResult VerificarEmail()
        {
            return View();
        }

        public IActionResult ErroEmail()
        {
            return View();
        }

        public IActionResult EscolherMetodo()
        {
            return View();
        }

        public IActionResult MetodoIncorreto()
        {
            return View();
        }

        public IActionResult InserirCodigo()
        {
            return View();
        }

        public IActionResult NovaSenha()
        {
            return View();
        }
    }
}

Controllers/NoticiasController.cs
using Microsoft.AspNetCore.Mvc;
using GWI.Repositories.ADO.SQLServer;
using GWI.Models.Noticias;
using GWI.Models.Imagens;
using System.Configuration;

namespace GWI.Controllers
{
    public class NoticiasController : Controller
    {
        private readonly Repositories.ADO.SQLServer.NoticiaADO repository;

        public NoticiasController(IConfiguration configuration)
        { 
            this.repository = new Repositories.ADO.SQLServer.NoticiaADO(configuration.GetConnectionString(Configurations.Appsettings.getKeyConnectionString()));
        }

        // Crud de Notícia //
        #region
        [HttpGet]
        public ActionResult Index()
        {
            return View(this.repository.get());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(this.repository.GetById(id));
        }

        [HttpGet]
        public ActionResult Create(int p_id)
        {
            ViewBag.p_id = 3;
            ViewBag.CategoriasList = this.repository.GetCategorias();
            ViewBag.SubcategoriasList = this.repository.GetSubcategorias();
            ViewBag.ImagensList = this.repository.GetImagens();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Noticias noticias, int p_id)
        {
            try
            {
                noticias.nt_p_id = p_id;
                this.repository.add(noticias);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(this.repository.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Noticias noticias)
        {
            try
            {
                this.repository.update(id, noticias);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            this.repository.delete(id);
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Views/Login/CadastrarUsuario.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro">
        <h2 class="titulo-cadastro">Cadastro</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <form class="form-cadastro" action="enviar.function" method="post">
            <label class="label-cadastro" for="primeiro-nome">Primeiro Nome:</label>
            <input class="input-cadastro" type="text" id="primeiro-nome" name="primeiro-nome" placeholder="Ex: Joãozinho">

            <label class="label-cadastro" for="sobrenomes">Sobrenomes:</label>
            <input class="input-cadastro" type="text" id="sobrenomes" name="sobrenomes" placeholder="Ex: Sobrenome1 Sobrenome2...">

            <p class="label-cadastro">Telefone:</p>
            <div>
                <input class="input-cadastro" type="tel" id="ddd" name="ddd" placeholder="DDD">
                <input class="input-cadastro" type="tel" id="telefone" name="telefone" placeholder="Número">
            </div>

            <label class="label-cadastro" for="email">Email:</label>
            <input class="input-cadastro" type="email" id="email" name="email" placeholder="Ex: joaozinho@email.com">

            <label class="label-cadastro" for="senha">Senha:</label>
            <input class="input-cadastro" type="password" id="senha" name="senha">

            <label class="label-cadastro" for="conf-senha">Confirmar Senha:</label>
            <input class="input-cadastro" type="password" id="conf-senha" name="conf-senha">

            <a asp-controller="Login" asp-action="FazerLogin">
                <input class="submit-cadastro" type="submit" value="Ok">
            </a>
        </form>
    </section>
</main>

Views/Login/ErroEmail.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h3 class="subtitulo-cadastro">O Email Inserido não Foi Encontrado em Nossa Base de Dados</h3>

        <a asp-controller="Login" asp-action="VerificarEmail">
            <button class="submit-cadastro">Ok</button>
        </a>
    </section>
</main>

Views/Login/EscolherMetodo.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h2 class="titulo-cadastro">Recuperação de Senha</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <h3 class="subtitulo-cadastro">Selecione e Insira o Método de Envio do Código de Recuperação:</h3>

        <form class="form-cadastro">
            <div class="accordion-rec-sen">
                <div class="accordion-rec-sen-item">
                    <input type="radio" name="rec-senha" checked="checked" id="radio-rec-senha-1">
                    <label class="label-cadastro" for="radio-rec-senha-1">Email</label>
                    <div class="accordion-rec-sen-content">
                        <label class="label-rec-senha" for="email" id="collapseOne">
                            <input class="input-cadastro input-rec-senha" type="email" id="email" name="email" placeholder="Ex: joaozinho@email.com">
                        </label>
                    </div>
                </div>

                <div class="accordion-rec-sen-item">
                    <input type="radio" name="rec-senha" id="radio-rec-senha-2">
                    <label class="label-cadastro" for="radio-rec-senha-2">Telefone</label>
                    <div class="accordion-rec-sen-content">
                        <label class="label-rec-senha" for="tel-rec-senha" id="collapseTwo">
                            <input class="input-cadastro input-rec-senha" type="tel" id="tel-rec-senha" name="tel-rec-senha" placeholder="Ex: 16997610798">
                        </label>
                    </div>
                </div>
            </div>

            <a asp-controller="Login" asp-action="InserirCodigo">
                <input class="submit-cadastro" type="submit" value="Ok">
            </a>
            <a asp-controller="Login" asp-action="MetodoIncorreto">.</a>
        </form>
    </section>
</main>

Views/Login/FazerLogin.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro login">
        <h2 class="titulo-cadastro">Login</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <form class="form-cadastro">
            <label class="label-cadastro" for="email">Email:</label>
            <input class="input-cadastro" type="email" id="email" name="email" placeholder="Ex: joazinho@email.com">

            <label class="label-cadastro" for="senha">Senha:</label>
            <input class="input-cadastro" type="password" id="senha" name="senha">
            <a asp-controller="Login" asp-action="VerificarEmail" class="link-recuperar-senha">Recuperar Senha</a>

            <div class="container-login-3o">
                <button class="botao-login-3o">
                    <img src="~/img/index/google.png" alt="entrar com google" class="img-login-3o">
                </button>
                <button class="botao-login-3o">
                    <img src="~/img/index/facebook.png" alt="entrar com facebook" class="img-login-3o">
                </button>
            </div>
            <div>
                <a asp-controller="Noticias" asp-action="Index">
                    <input class="submit-cadastro dois-botoes-esquerda" type="submit" value="Entrar">
                </a>
                <a asp-controller="Pessoas" asp-action="Create">
                    <button class="submit-cadastro dois-botoes-direita" type="button">Cadastre-Se</button>
                </a>
            </div>
        </form>
    </section>
</main>

Views/Login/InserirCodigo.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h2 class="titulo-cadastro">Recuperação de Senha</h2>

        <button class="cadastro-close-button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
            </svg>
        </button>

        <h3 class="subtitulo-cadastro">Insira o Código Enviado Para:</h3>
        <p class="p-cadastro">usuario@email.com</p>

        <form class="form-cadastro" action="enviar.function" method="post">
            <label class="label-cadastro" for="inserir-codigo">Código:</label>
            <input class="input-cadastro" type="text" id="inserir-codigo" placeholder="Ex: 0000 0000">

            <a asp-controller="Login" asp-action="NovaSenha">
                <input class="submit-cadastro" type="submit" value="Ok">
            </a>
        </form>
    </section>
</main>

Views/Login/MetodoIncorreto.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h3 class="subtitulo-cadastro">O Método de Recuperação Selecionado não Foi Encontrado em Nossa Base de Dados</h3>

        <a asp-controller="Login" asp-action="EscolherMetodo">
            <button class="submit-cadastro">Ok</button>
        </a>
    </section>
</main>

Views/Login/NovaSenha.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h2 class="titulo-cadastro">Redefinição de Senha</h2>

        <button class="cadastro-close-button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
            </svg>
        </button>

        <form class="form-cadastro" action="enviar.function" method="post">
            <label class="label-cadastro" for="senha">Nova Senha:</label>
            <input class="input-cadastro" type="password" id="senha" name="senha">

            <label class="label-cadastro" for="conf-senha">Confirmar Senha:</label>
            <input class="input-cadastro" type="password" id="conf-senha" name="conf-senha">

            <a asp-controller="Noticias" asp-action="Index">
                <input class="submit-cadastro" type="submit" value="Ok">
            </a>
        </form>
    </section>
</main>

Views/Login/VerificarEmail.cshtml
<!--  /main desktop/  -->
<main class="pag_sem_cotacoes">
    <!-- pagina de cadastro de usuario -->
    <section class="secao-cadastro rec-senha">
        <h2 class="titulo-cadastro">Redefinição de Senha</h2>

        <a asp-controller="Noticias" asp-action="Index">
            <button class="cadastro-close-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#141414" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                </svg>
            </button>
        </a>

        <h3 class="subtitulo-cadastro">Insira o Email Cadastrado</h3>

        <form class="form-cadastro">
            <label class="label-cadastro" for="email">Email:</label>
            <input class="input-cadastro" type="email" id="email" name="email" placeholder="Ex: usuario@email.com">
            
            <a asp-controller="Login" asp-action="EscolherMetodo">
                <input class="submit-cadastro" type="submit" value="Ok">
            </a>

            <a asp-controller="Login" asp-action="ErroEmail">.</a>
        </form>
    </section>
</main>